import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, Coins, Cpu, Crown, Database, Gamepad2, Globe2, MessageCircle, Rocket, Server, ShieldCheck, Sparkles, Target, Trophy, Users, Zap } from "lucide-react";
import "./whitepaper.css";

export const metadata: Metadata = { title: "Whitepaper | FLANTO AI", description: "Visão, tração, jogos, tecnologia e roadmap de expansão do ecossistema FLANTO AI." };

const chapters = [
  ["visao-geral", "01", "Visão geral"], ["problema", "02", "O problema"], ["solucao", "03", "A solução"], ["tracao", "04", "Tração atual"],
  ["como-funciona", "05", "Como funciona"], ["jogos", "06", "Ecossistema de jogos"], ["progressao", "07", "Pontos e ranking"], ["boosts", "08", "Boosts"],
  ["comunidades", "09", "Comunidades"], ["seguranca", "10", "Segurança"], ["roadmap", "11", "Roadmap"], ["investimento", "12", "Oportunidade"],
];

function ChapterNav() { return <nav className="wp-chapters" aria-label="Capítulos do whitepaper">{chapters.map(([id, number, label]) => <a key={id} href={`#${id}`}><span>{number}</span>{label}</a>)}</nav>; }

export default function Whitepaper() {
  return <main className="whitepaper-page">
    <header className="wp-header"><a className="wp-brand" href="/"><img src="/flanto-logo-new.webp" alt="" /><span>FLANTO <b>AI</b></span></a><div className="wp-doc-label"><BookOpen size={16} /> WHITEPAPER <span>v1.1</span></div><a className="wp-back" href="/"><ArrowLeft size={16} /> Voltar ao site</a></header>
    <details className="wp-mobile-index"><summary><BookOpen size={17} /> Navegar pelos capítulos</summary><ChapterNav /></details>
    <div className="wp-layout">
      <aside className="wp-sidebar"><p>DOCUMENTAÇÃO</p><ChapterNav /><div className="wp-sidebar-card"><MessageCircle size={18} /><strong>Quer experimentar?</strong><span>Adicione o FLANTO ao seu grupo.</span><a href="https://wa.me/5569992308771" target="_blank" rel="noreferrer">Abrir WhatsApp <ArrowRight size={14} /></a></div></aside>
      <article className="wp-content">
        <section className="wp-intro" id="visao-geral"><span className="wp-kicker">WHITEPAPER OFICIAL • SETEMBRO 2026</span><h1>Comunidades mais vivas.<br /><em>Conexões mais fortes.</em></h1><p className="wp-lead">O FLANTO AI é uma plataforma de jogos, competição, moderação e automações que funciona dentro do WhatsApp. Este documento apresenta a visão, a tração construída e o caminho para transformar o produto em um ecossistema global.</p><div className="wp-meta"><span><BookOpen size={16} /> 12 capítulos</span><span><Clock3 size={16} /> 12 min de leitura</span><span><Check size={16} /> Versão 1.1</span></div></section>

        <section id="problema"><span className="wp-number">02</span><h2>O problema</h2><p>Grupos digitais nascem para aproximar pessoas, mas frequentemente perdem ritmo. A conversa se concentra em poucos membros, a moderação consome tempo e não existe uma dinâmica contínua que transforme presença em participação.</p><div className="wp-stat-grid"><div><strong>Baixa participação</strong><span>Muitos membros observam, poucos interagem.</span></div><div><strong>Rotina manual</strong><span>Administradores repetem tarefas todos os dias.</span></div><div><strong>Sem continuidade</strong><span>A animação de um evento desaparece rapidamente.</span></div></div></section>

        <section id="solucao"><span className="wp-number">03</span><h2>A solução FLANTO</h2><p>O FLANTO transforma o próprio grupo em um espaço de jogo e convivência. Sem exigir outro aplicativo, ele conduz partidas, registra pontos, organiza rankings e apoia administradores com ferramentas de gestão.</p><div className="wp-principles"><article><Gamepad2 /><h3>Jogar onde a comunidade já está</h3><p>A experiência acontece dentro do WhatsApp, reduzindo barreiras para começar.</p></article><article><Users /><h3>Participação compartilhada</h3><p>Jogos curtos criam motivos frequentes para conversar e voltar ao grupo.</p></article><article><ShieldCheck /><h3>Automação com controle</h3><p>Recursos administrativos ficam restritos a pessoas autorizadas.</p></article></div></section>

        <section id="tracao"><span className="wp-number">04</span><h2>Tração construída com produto real</h2><p>O FLANTO já saiu do campo da ideia. A plataforma opera com usuários cadastrados, comunidades ativas, jogos em produção e uma dinâmica nacional de competição. Essa base reduz o risco inicial e cria um ponto de partida concreto para a próxima fase.</p><div className="wp-traction"><article><strong>70+</strong><span>usuários cadastrados</span></article><article><strong>30+</strong><span>grupos alcançados</span></article><article><strong>16</strong><span>jogos disponíveis</span></article><article><strong>2</strong><span>jogos autorais</span></article></div><div className="wp-proof"><div><Users /><span><strong>Jogadores ativos</strong>Participação recorrente dentro das comunidades.</span></div><div><Trophy /><span><strong>Ranking nacional</strong>Competição conectando jogadores de diferentes grupos.</span></div><div><Rocket /><span><strong>Produto em operação</strong>Tecnologia própria funcionando diariamente no WhatsApp.</span></div></div><p className="wp-data-note">Dados informados pela equipe do FLANTO AI até 21 de setembro de 2026.</p></section>

        <section id="como-funciona"><span className="wp-number">05</span><h2>Como funciona</h2><div className="wp-flow"><div><b>1</b><span><strong>Salvar</strong>Salve o número oficial do FLANTO.</span></div><div><b>2</b><span><strong>Adicionar</strong>Inclua o FLANTO na comunidade.</span></div><div><b>3</b><span><strong>Jogar</strong>Envie <code>/jogos</code> e escolha uma experiência.</span></div></div><p>As interações são guiadas por mensagens e comandos simples. O FLANTO apresenta regras, controla cada rodada e informa os resultados no mesmo ambiente em que o grupo já conversa.</p></section>

        <section id="jogos"><span className="wp-number">06</span><h2>Ecossistema de jogos</h2><p>O catálogo reúne 16 jogos e combina estratégia, conhecimento, velocidade e criatividade. FLANTO City e Acerte o Desenho são experiências autorais do projeto, criadas para fortalecer uma identidade própria e ampliar o potencial do ecossistema.</p><div className="wp-game-list"><article><img src="/flanto-city.webp" alt="Arte oficial do FLANTO City" /><div><span>ESTRATÉGIA • AUTORAL</span><h3>FLANTO City</h3><p>Papéis secretos e dedução social em uma experiência criada pelo FLANTO.</p></div></article><article><img src="/acerte-desenho.webp" alt="Arte oficial do Acerte o Desenho" /><div><span>CRIATIVIDADE • AUTORAL</span><h3>Acerte o Desenho</h3><p>Um desenha e o grupo disputa para descobrir primeiro.</p></div></article><article><img src="/anagrama.webp" alt="Arte oficial do Anagrama" /><div><span>VELOCIDADE</span><h3>Anagrama</h3><p>Letras embaralhadas, respostas rápidas e pontos em disputa.</p></div></article><article><img src="/quiz.webp" alt="Arte oficial do Quiz" /><div><span>CONHECIMENTO</span><h3>Quiz</h3><p>Perguntas e alternativas para movimentar toda a comunidade.</p></div></article></div></section>

        <section id="progressao"><span className="wp-number">07</span><h2>Pontos, ranking e temporadas</h2><p>A progressão dá continuidade às partidas. Resultados geram pontos, o ranking compara desempenhos e as temporadas criam ciclos renovados de competição.</p><div className="wp-system"><div><Sparkles /><strong>Participe</strong><span>Jogue e conclua desafios.</span></div><ArrowRight /><div><Zap /><strong>Pontue</strong><span>Acumule pontos nas partidas.</span></div><ArrowRight /><div><Trophy /><strong>Suba</strong><span>Avance no ranking da temporada.</span></div></div><div className="wp-note"><Trophy /><p><strong>Ranking conectado</strong> A página principal consulta periodicamente o ranking do FLANTO e identifica quando os dados exibidos são ao vivo ou o último retrato confirmado.</p></div></section>

        <section id="boosts"><span className="wp-number">08</span><h2>Boosts de pontos</h2><p>Boosts são multiplicadores temporários para quem quer acelerar sua progressão. Eles não acumulam: ativar um plano superior encerra o anterior.</p><div className="wp-boosts"><article><span>x2</span><strong>24 horas</strong><b>R$ 1,99</b></article><article><span>x3</span><strong>24 horas</strong><b>R$ 4,99</b></article><article><span>x4</span><strong>7 dias</strong><b>R$ 9,99</b></article></div></section>

        <section id="comunidades"><span className="wp-number">09</span><h2>Valor para toda a comunidade</h2><div className="wp-split"><article><Gamepad2 /><h3>Para quem joga</h3><ul><li>Jogos e desafios frequentes</li><li>Rankings e temporadas</li><li>Pontos e Boosts</li><li>Experiências exclusivas</li></ul></article><article><Crown /><h3>Para quem administra</h3><ul><li>Moderação e anti-spam</li><li>Lembretes automáticos</li><li>Abertura e fechamento</li><li>Rotinas inteligentes</li></ul></article></div></section>

        <section id="seguranca"><span className="wp-number">10</span><h2>Segurança e responsabilidade</h2><p>O FLANTO foi desenhado para apoiar comunidades sem retirar o controle de seus administradores. Comandos sensíveis são reservados a pessoas autorizadas, e a experiência prioriza regras claras para participantes.</p><div className="wp-note"><ShieldCheck /><p><strong>Transparência do produto</strong> O FLANTO é um produto independente e não possui afiliação com o WhatsApp. Este documento apresenta visão e planejamento de produto; não constitui oferta pública, promessa de retorno ou recomendação de investimento.</p></div></section>

        <section id="roadmap"><span className="wp-number">11</span><h2>Roadmap de expansão</h2><p>O FLANTO já construiu a fundação do produto. A próxima etapa é transformar uma solução validada em uma infraestrutura de entretenimento e comunidade preparada para crescer no Brasil e internacionalmente.</p><div className="wp-roadmap"><article className="done"><span>FASE 01 • CONCLUÍDA</span><h3>Fundação e validação</h3><p>Produto em operação no WhatsApp, 16 jogos, 2 experiências autorais, cadastro de usuários, pontos, ranking nacional, moderação, automações e Boosts.</p></article><article className="current"><span>FASE 02 • EM EVOLUÇÃO</span><h3>Performance e conteúdo</h3><p>Expandir servidores e capacidade de processamento; tornar respostas e partidas mais rápidas; ampliar e revisar os bancos de perguntas; adicionar novos jogos conforme a infraestrutura crescer; reforçar estabilidade e recuperação automática.</p></article><article><span>FASE 03 • PRODUTO INTELIGENTE</span><h3>IA de nova geração</h3><p>Integrar modelos de inteligência artificial de alto desempenho para personalização, criação de conteúdo, suporte a administradores, moderação contextual e experiências adaptadas a cada comunidade.</p></article><article><span>FASE 04 • MULTIPLATAFORMA</span><h3>Além do WhatsApp</h3><p>Levar a experiência FLANTO para Discord, Telegram e outras plataformas relevantes, preservando identidade, progressão e ranking entre diferentes comunidades.</p></article><article><span>FASE 05 • WEB3</span><h3>Economia digital do ecossistema</h3><p>Preparar pagamentos em criptoativos, missões verificáveis, campanhas de airdrop e um token próprio com utilidade dentro do projeto. Qualquer lançamento dependerá de desenho econômico responsável, segurança técnica, auditoria e conformidade jurídica.</p></article><article><span>FASE 06 • INTERNACIONAL</span><h3>Escala global</h3><p>Localização para novos idiomas, marketing internacional, parcerias estratégicas e adaptação cultural dos jogos para formar comunidades FLANTO em diferentes mercados.</p></article></div><div className="wp-roadmap-grid"><article><Server /><h3>Infraestrutura</h3><p>Mais capacidade, disponibilidade e segurança para sustentar crescimento.</p></article><article><Database /><h3>Conteúdo</h3><p>Bancos maiores, revisados e preparados para novas categorias.</p></article><article><Cpu /><h3>Inteligência artificial</h3><p>Modelos melhores para automação e experiências personalizadas.</p></article><article><Globe2 /><h3>Distribuição global</h3><p>Novos idiomas, plataformas, parcerias e aquisição internacional.</p></article><article><Coins /><h3>Web3 responsável</h3><p>Cripto, missões, airdrops e token com utilidade real.</p></article><article><Gamepad2 /><h3>Propriedade intelectual</h3><p>Mais jogos autorais capazes de fortalecer a marca FLANTO.</p></article></div></section>

        <section id="investimento"><span className="wp-number">12</span><h2>Uma oportunidade de acelerar o que já funciona</h2><p>O FLANTO não busca investimento para descobrir se a ideia funciona. O produto já possui tecnologia, jogos, usuários e comunidades. O capital será direcionado para remover limites de infraestrutura, acelerar distribuição e transformar a tração inicial em escala.</p><div className="wp-investment"><article><span>01</span><Target /><h3>Produto</h3><p>Engenharia, servidores, segurança, IA, novos jogos e evolução das propriedades autorais.</p></article><article><span>02</span><Globe2 /><h3>Crescimento</h3><p>Marketing nacional e internacional, conteúdo, aquisição de comunidades e parcerias.</p></article><article><span>03</span><Rocket /><h3>Expansão</h3><p>Novas plataformas, idiomas, pagamentos digitais e preparação do ecossistema Web3.</p></article></div><div className="wp-thesis"><strong>Por que agora?</strong><p>A primeira metade do caminho já foi construída: existe um produto real, uma comunidade inicial e sinais concretos de uso. O investimento encurta o caminho entre validação e escala.</p></div><a className="wp-investor-cta" href="https://wa.me/5569992308771?text=Ol%C3%A1%2C%20quero%20conhecer%20a%20oportunidade%20de%20investimento%20do%20FLANTO%20AI." target="_blank" rel="noreferrer">Conversar sobre investimento <ArrowRight size={17} /></a></section>

        <section className="wp-closing"><img src="/flanto-logo-new.webp" alt="Símbolo do FLANTO AI" /><span>COMECE GRATUITAMENTE</span><h2>Pronto para dar vida<br />à sua comunidade?</h2><a href="https://wa.me/5569992308771" target="_blank" rel="noreferrer">Abrir no WhatsApp <ArrowRight size={17} /></a></section>
        <footer className="wp-footer"><span>FLANTO AI • Whitepaper v1.1</span><span>Atualizado em 21 de setembro de 2026</span></footer>
      </article>
      <aside className="wp-outline" aria-label="Nesta página"><p>NESTA PÁGINA</p><a href="#visao-geral">Introdução</a><a href="#tracao">Tração</a><a href="#jogos">Jogos</a><a href="#progressao">Progressão</a><a href="#roadmap">Roadmap</a><a href="#investimento">Investimento</a></aside>
    </div>
  </main>;
}
